// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-trabalhos.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient } from "npm:@supabase/supabase-js@^2.101.0";
import { z } from "npm:zod@^3.25.76";
var SUPABASE_URL = "https://zqoywwtdsbtqtytvyzwl.supabase.co";
var SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpxb3l3d3Rkc2J0cXR5dHZ5endsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0ODcxODYsImV4cCI6MjA5MTA2MzE4Nn0.r2NXJ5bh9fYntoZoDaMFYUmdp5u5zJC9zYJ46gZVWuM";
var list_trabalhos_default = defineTool({
  name: "list_trabalhos_auditoria",
  title: "Listar trabalhos de auditoria",
  description: "Lista trabalhos de auditoria acess\xEDveis ao usu\xE1rio autenticado (respeita RLS). Retorna id, cliente_id, exercicio_id e status.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("N\xFAmero m\xE1ximo de trabalhos a retornar (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "N\xE3o autenticado." }],
        isError: true
      };
    }
    const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("trabalhos_auditoria").select("id, cliente_id, exercicio_id, status, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) {
      return {
        content: [{ type: "text", text: `Erro: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { trabalhos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-clientes.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.0";
import { z as z2 } from "npm:zod@^3.25.76";
var SUPABASE_URL2 = "https://zqoywwtdsbtqtytvyzwl.supabase.co";
var SUPABASE_ANON_KEY2 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpxb3l3d3Rkc2J0cXR5dHZ5endsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0ODcxODYsImV4cCI6MjA5MTA2MzE4Nn0.r2NXJ5bh9fYntoZoDaMFYUmdp5u5zJC9zYJ46gZVWuM";
var list_clientes_default = defineTool2({
  name: "list_clientes",
  title: "Listar clientes",
  description: "Lista clientes acess\xEDveis ao usu\xE1rio autenticado (respeita RLS). Retorna id, raz\xE3o social e nome fantasia.",
  inputSchema: {
    limit: z2.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "N\xE3o autenticado." }],
        isError: true
      };
    }
    const supabase = createClient2(SUPABASE_URL2, SUPABASE_ANON_KEY2, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("clientes").select("id, razao_social, nome_fantasia").order("razao_social", { ascending: true }).limit(limit ?? 100);
    if (error) {
      return {
        content: [{ type: "text", text: `Erro: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { clientes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-mcse-conta.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.101.0";
import { z as z3 } from "npm:zod@^3.25.76";
var SUPABASE_URL3 = "https://zqoywwtdsbtqtytvyzwl.supabase.co";
var SUPABASE_ANON_KEY3 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpxb3l3d3Rkc2J0cXR5dHZ5endsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0ODcxODYsImV4cCI6MjA5MTA2MzE4Nn0.r2NXJ5bh9fYntoZoDaMFYUmdp5u5zJC9zYJ46gZVWuM";
var get_mcse_conta_default = defineTool3({
  name: "get_mcse_conta",
  title: "Buscar conta MCSE",
  description: "Busca uma conta can\xF4nica do MCSE pelo c\xF3digo. Retorna descri\xE7\xE3o, grupo e subgrupo.",
  inputSchema: {
    codigo: z3.string().trim().min(1).describe("C\xF3digo da conta MCSE.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ codigo }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "N\xE3o autenticado." }],
        isError: true
      };
    }
    const supabase = createClient3(SUPABASE_URL3, SUPABASE_ANON_KEY3, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("mcse_contas").select("*").eq("codigo", codigo).maybeSingle();
    if (error) {
      return {
        content: [{ type: "text", text: `Erro: ${error.message}` }],
        isError: true
      };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: `Nenhuma conta MCSE encontrada para o c\xF3digo ${codigo}.` }]
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { conta: data }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "audiconsult-mcp",
  title: "Audiconsult Auditoria \u2014 MCP",
  version: "0.1.0",
  instructions: "Ferramentas de leitura sobre trabalhos de auditoria, clientes e contas MCSE do sistema Audiconsult. Todas as chamadas respeitam a identidade do usu\xE1rio autenticado (RLS).",
  auth: auth.oauth.issuer({
    issuer: "https://zqoywwtdsbtqtytvyzwl.supabase.co/auth/v1",
    acceptedAudiences: "authenticated"
  }),
  tools: [list_trabalhos_default, list_clientes_default, get_mcse_conta_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
